package com.capgemini.heskuelita.core.beans;

import lombok.*;

//Autoenerated Getters,Setters, and ALL args constructor, using Lambok
@Data
//Autogenerated no args constructor, using lambok.
@NoArgsConstructor
public class User {

    //Declaration of users atributes
    private String userName;
    private String password;
    private String email;

}
